languageCode = "en-us"
title = "Web3 Teacher Training Track"
baseURL = "https://web3.courses/"
ignoreFiles = ["_slides.md$"]
themesDir = "themes"
publishDir = "docs"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Course"
  url = "/teacher-training-track"
  weight = 2

[[menu.main]]
  name = "Apply"
  url = "/apply"
  weight = 3
  [menu.main.params]
    target = "_blank"

[params]
  google_analytics_id=""
  homepage_button_link = "/teacher-training-track"
  homepage_button_text = "View Course"
  homepage_intro = "The Blockchain Acceleration Foundation's Web3 Teacher Training Track is a dApp and smart contract development course"
  homepage_image = "/images/logo.png"

  ## You can enable to add anchor links to header elements
  # enable_anchor_link = true

  [params.homepage_meta_tags]
    meta_description = "The Blockchain Acceleration Foundation's Web3 Teacher Training Track is a dApp and smart contract development course"
    meta_og_title = "Web3 Teacher Training Track"
    meta_og_type = "website"
    meta_og_url = ""
    meta_og_image = ""
    meta_og_description = "The Blockchain Acceleration Foundation's Web3 Teacher Training Track is a dApp and smart contract development course"
    meta_twitter_card = "summary"
    meta_twitter_site = "@TheBAFNetwork"
    meta_twitter_creator = "@TheBAFNetwork"

  [params.logo]
    mobile = "/images/icon.png"
    standard  = "/images/icon.png"

[outputFormats]
  [outputFormats.slides]
    baseName = "slides"
    isHTML = true
    permalinkable = true
    mediaType = "text/html"
